from django.db import models

class CallList(models.Model):
    callKey = models.CharField(max_length=200, blank=True, null=True)
    disposition = models.CharField(max_length=200, blank=True, null=True)
    hangupcause = models.CharField(max_length=200, blank=True, null=True)
    assigned = models.CharField(max_length=200, blank=True, null=True)
    campaign_name = models.CharField(max_length=200, blank=True, null=True)
    attendant_overflow = models.CharField(max_length=200, blank=True, null=True)
    holdduration = models.CharField(max_length=200, blank=True, null=True)
    click2call =models.CharField(max_length=200, blank=True, null=True)
    initialqueue = models.CharField(max_length=200, blank=True, null=True)
    callerid = models.CharField(max_length=200, blank=True, null=True)
    campaignqueuekey = models.CharField(max_length=200, blank=True, null=True)
    answered = models.CharField(max_length=200, blank=True, null=True)
    flag_csat = models.CharField(max_length=200, blank=True, null=True)
    voicemailtotext = models.CharField(max_length=200, blank=True, null=True)
    sourcetenant = models.CharField(max_length=200, blank=True, null=True)
    inbound = models.CharField(max_length=200, blank=True, null=True)
    callid = models.CharField(max_length=200, blank=True, null=True)
    uniqueid = models.CharField(max_length=200, blank=True, null=True, unique=True)
    recordingurl = models.CharField(max_length=200, blank=True, null=True)
    hold = models.CharField(max_length=200, blank=True, null=True)
    called_num = models.CharField(max_length=200, blank=True, null=True)
    transferred = models.IntegerField(default=0)
    csat_answers = models.CharField(max_length=200, blank=True, null=True)
    channel = models.CharField(max_length=200, blank=True, null=True)
    abandon = models.CharField(max_length=200, blank=True, null=True)
    agentid = models.CharField(max_length=200, blank=True, null=True)
    queued = models.CharField(max_length=200, blank=True, null=True)
    status = models.CharField(max_length=200, blank=True, null=True)
    agent = models.CharField(max_length=200, blank=True, null=True)
    waitduration = models.IntegerField(default=0)
    duration = models.CharField(max_length=200, blank=True, null=True)
    queuekey = models.CharField(max_length=200, blank=True, null=True)
    black_list = models.CharField(max_length=200, blank=True, null=True)
    calldate = models.CharField(max_length=200, blank=True, null=True)
    answeredby = models.CharField(max_length=200, blank=True, null=True)
    shortcall = models.CharField(max_length=200, blank=True, null=True)
    localrelease =models.CharField(max_length=200, blank=True, null=True)
    csat_score = models.IntegerField(default=0)
    csat = models.CharField(max_length=200, blank=True, null=True)
    wrapup_code = models.CharField(max_length=200, blank=True, null=True)
    agentkey = models.CharField(max_length=200, blank=True, null=True)
    csat_completed = models.CharField(max_length=200, blank=True, null=True)
    Voicemail = models.CharField(max_length=200, blank=True, null=True)
    customvariables = models.CharField(max_length=200, blank=True, null=True)
    key = models.CharField(max_length=200, blank=True, null=True)
    hangupdate = models.CharField(max_length=200, blank=True, null=True)
    queuedate = models.CharField(max_length=200, blank=True, null=True)
    queue = models.CharField(max_length=200, blank=True, null=True)
    voicemail_duration = models.IntegerField(default=0)
    contactkey = models.CharField(max_length=200, blank=True, null=True)
    talkdate = models.CharField(max_length=200, blank=True, null=True, default="")
    sl = models.CharField(max_length=200, blank=True, null=True)
    acddate = models.CharField(max_length=200, blank=True, null=True)






